apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lmagniez03-dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'frontend'
        static_configs:
          - targets: ['frontend.lmagniez03-dev.svc.cluster.local:8080']
    rule_files:
      - "rules/*.yaml"
