apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lmagniez03-dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    rule_files:
      - "/etc/prometheus/rules/*.yaml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
