apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: main
  workspaces:
    - name: shared-data
      description: Workspace to clone the repository into
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone --branch $(params.revision) $(params.repo-url) $(workspaces.shared-data.path)
