apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: front-build-run-2
  annotations:
    pipelinesascode.tekton.dev/on-event: "push,pull_request"
    pipelinesascode.tekton.dev/on-target-branch: ".*"
    pipelinesascode.tekton.dev/when-modified: "front/**"
spec:
  pipelineRef:
    name: front-build-pipeline
  params:
    - name: repo-url
      value: https://github.com/CCM2023-OpenShift/m2ccm-OpenshiftProject.git
    - name: revision
      value: main
  workspaces:
    - name: shared-data
      emptyDir: {}
