apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: network-policy-run-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push, pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/when-modified: ["infrastructure/keycloak/**"]
spec:
  pipelineRef:
    name: network-policy-pipeline
  params:
    - name: repo-url
      value: https://github.com/CCM2023-OpenShift/m2ccm-OpenshiftProject.git
    - name: revision
      value: main

