apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-sa
  namespace: gregorydhmccm-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gregorydhmccm-dev
  name: argocd-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["appprojects", "applications", "repos", "clusters"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rolebinding
  namespace: gregorydhmccm-dev
subjects:
  - kind: ServiceAccount
    name: argocd-sa
    namespace: gregorydhmccm-dev
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
