apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: lmagniez03-dev
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
