apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: lmagniez03-dev
  labels:
    grafana_datasource: "true"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.lmagniez03-dev.svc.cluster.local:9090
        isDefault: true
        editable: true
