apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-postgresql
  namespace: lmagniez03-dev
spec:
  podSelector:
    matchLabels:
      app: postgresql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: quarkus-app
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-quarkus-egress
  namespace: lmagniez03-dev
spec:
  podSelector:
    matchLabels:
      app: quarkus-app
  policyTypes: [Egress]
  egress:
  - {}
