apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: gregorydhmccm-dev
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel9/postgresql-15
          env:
            - name: POSTGRESQL_DATABASE
              value: "mydatabase"
            - name: POSTGRESQL_USER
              value: "quarkus"
            - name: POSTGRESQL_PASSWORD
              value: "QuarkusSecret"
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: "MySuperSecret"
            - name: POSTGRES_INITDB_ARGS
              value: "--nosync --no-locale --username=admin"
            - name: PGDATA
              value: "/var/lib/pgsql/data"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgresql-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: gregorydhmccm-dev
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
