apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: quarkus-app
  namespace: lmagniez03-dev
spec:
  source:
    type: Binary
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: quarkus-app:latest

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: quarkus-app
  namespace: lmagniez03-dev
