apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app
  namespace: gregorydhmccm-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-app
  template:
    metadata:
      labels:
        app: quarkus-app
    spec:
      containers:
        - name: quarkus-app
          image: image-registry.openshift-image-registry.svc:5000/gregorydhmccm-dev/quarkus-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_PROFILE
              value: "prod"
            - name: IMAGE_UPLOAD_DIRECTORY
              value: "/uploads/images"
            - name: APP_SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase
                  key: APP_SUPABASE_KEY
            - name: APP_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase
                  key: APP_SUPABASE_URL
            - name: PROD_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: quarkus-secrets
                  key: PROD_DB_USERNAME
            - name: PROD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quarkus-secrets
                  key: PROD_DB_PASSWORD
            - name: PROD_KC_SECRET
              valueFrom:
                secretKeyRef:
                  name: quarkus-secrets
                  key: PROD_KC_SECRET
            - name: PROD_KC_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: PROD_KC_SERVICE_SECRET
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN_PASSWORD

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
  namespace: gregorydhmccm-dev
spec:
  selector:
    app: quarkus-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quarkus-route
  namespace: gregorydhmccm-dev
spec:
  to:
    kind: Service
    name: quarkus-service
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None