apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: lmagniez03-dev
data:
  myrealm.json: |
    {
      "realm": "myrealm",
      "enabled": true,
      "users": [
        {
          "username": "user1",
          "enabled": true,
          "credentials": [{ "type": "password", "value": "password1" }],
          "realmRoles": ["user"]
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "user"
          },
          {
            "name": "admin"
          }
        ]
      },
      "clients": [
        {
          "clientId": "my-app",
          "redirectUris": [
            "https://vite-oc-lmagniez03-dev.apps.rm2.thpm.p1.openshiftapps.com/*"
          ],
          "webOrigins": [
            "https://vite-oc-lmagniez03-dev.apps.rm2.thpm.p1.openshiftapps.com"
          ],
          "publicClient": true,
          "directAccessGrantsEnabled": true
        }
      ]
    }
