apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-dev
  namespace: gregorydhmccm-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-dev
  template:
    metadata:
      labels:
        app: keycloak-dev
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          args:
            - start-dev
            - --import-realm
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret-dev
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret-dev
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://keycloak-postgresql-dev:5432/keycloakdbdev"
            - name: KC_DB_USERNAME
              value: "keycloakdbdev"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql-secret-dev
                  key: POSTGRES_PASSWORD
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KEYCLOAK_CORS
              value: "true"
            - name: KEYCLOAK_CORS_ALLOWED_ORIGINS
              value: "http://localhost:3000"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME
              value: "keycloak-dev-gregorydhmccm-dev.apps.rm1.0a51.p1.openshiftapps.com"
            - name: KC_SPI_EMAIL_SENDER_FROM
              value: "doriandu02100@gmail.com"
            - name: KC_SPI_EMAIL_SENDER_HOST
              value: "smtp.gmail.com"
            - name: KC_SPI_EMAIL_SENDER_PORT
              value: "587"
            - name: KC_SPI_EMAIL_SENDER_STARTTLS
              value: "true"
            - name: KC_SPI_EMAIL_SENDER_AUTH
              value: "true"
            - name: KC_SPI_EMAIL_SENDER_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-smtp-secret
                  key: USERNAME
            - name: KC_SPI_EMAIL_SENDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-smtp-secret
                  key: PASSWORD
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm-config-dev

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-dev
  namespace: gregorydhmccm-dev
spec:
  selector:
    app: keycloak-dev
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: keycloak-dev
  namespace: gregorydhmccm-dev
spec:
  host: keycloak-dev-gregorydhmccm-dev.apps.rm1.0a51.p1.openshiftapps.com
  to:
    kind: Service
    name: keycloak-dev
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect