apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: lmagniez03-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          args:
            - start-dev
            - --import-realm
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KEYCLOAK_URL
              value: "https://keycloak-lmagniez03-dev.apps.rm2.thpm.p1.openshiftapps.com"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY
              value: "edge"
            - name: KC_FRONTEND_URL
              value: "https://keycloak-lmagniez03-dev.apps.rm2.thpm.p1.openshiftapps.com"
            - name: KEYCLOAK_CORS
              value: "true"
            - name: KEYCLOAK_CORS_ALLOWED_ORIGINS
              value: "http://localhost:3000"
            - name: KEYCLOAK_CONTENT_SECURITY_POLICY
              value: "default-src 'self'; frame-src 'self' https://keycloak-lmagniez03-dev.apps.rm2.thpm.p1.openshiftapps.com"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm-config


---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: lmagniez03-dev
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: keycloak
  namespace: lmagniez03-dev
spec:
  to:
    kind: Service
    name: keycloak
  port:
    targetPort: http
  tls:
    termination: edge
