name: Deploy PostgreSQL on OpenShift

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/postgresql-deployment.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/postgresql-deployment.yaml'

jobs:
  deploy-postgresql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify
          oc project $OPENSHIFT_PROJECT

      - name: Apply PostgreSQL Deployment YAML
        env:
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          oc apply -f infrastructure/postgresql-deployment.yaml -n $OPENSHIFT_PROJECT

      - name: Wait for PostgreSQL to be Ready
        env:
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          echo "⌛ Waiting for PostgreSQL pod to be ready..."
          oc wait --for=condition=Available deployment/postgresql --timeout=120s -n $OPENSHIFT_PROJECT || echo "⚠️ PostgreSQL might not be ready yet."
