name: Build & Deploy Quarkus on OpenShift

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build Quarkus Application
        run: ./mvnw clean package -DskipTests

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify
          oc project $OPENSHIFT_PROJECT

      - name: Manage BuildConfig and ImageStream
        env:
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          echo "🔍 Vérification de l'ImageStream..."
          if ! oc get is quarkus-app -n $OPENSHIFT_PROJECT &>/dev/null; then
            echo "📦 Création de l'ImageStream..."
            oc create is quarkus-app -n $OPENSHIFT_PROJECT
          fi
          
          echo "🔍 Vérification du BuildConfig..."
          if ! oc get bc quarkus-app -n $OPENSHIFT_PROJECT &>/dev/null; then
            echo "🛠️ Création du BuildConfig..."
            oc new-build --binary --strategy=docker --name=quarkus-app -n $OPENSHIFT_PROJECT
          else
            echo "🔄 Mise à jour du BuildConfig existant..."
            oc patch bc quarkus-app -n $OPENSHIFT_PROJECT --type=merge -p '{"spec":{"source":{"dockerfilePath":"src/main/docker/Dockerfile.jvm"}}}'
          fi

      - name: Configure Build Resources
        env:
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          echo "⚙️ Configuration des ressources pour le build..."
          oc patch bc quarkus-app -n $OPENSHIFT_PROJECT --type=merge -p '{
            "spec": {
              "resources": {
                "limits": {
                  "memory": "2Gi",
                  "cpu": "1"
                },
                "requests": {
                  "memory": "1Gi",
                  "cpu": "500m"
                }
              }
            }
          }'

      - name: Clean up previous failed builds
        env:
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          echo "🧹 Nettoyage des builds échoués..."
          oc delete build -l buildconfig=quarkus-app,status=failed -n $OPENSHIFT_PROJECT --ignore-not-found=true

      - name: Build and Push Image to OpenShift ImageStream
        env:
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          echo "📝 Préparation du Dockerfile..."
          cp src/main/docker/Dockerfile.jvm Dockerfile
          
          echo "🚀 Démarrage d'un nouveau build..."
          timeout 15m oc start-build quarkus-app --from-dir=. --follow -n $OPENSHIFT_PROJECT || {
            echo "❌ Build échoué, vérification des logs..."
            BUILD_NAME=$(oc get builds -l buildconfig=quarkus-app -n $OPENSHIFT_PROJECT --sort-by=.metadata.creationTimestamp -o name | tail -n 1)
            oc logs $BUILD_NAME -n $OPENSHIFT_PROJECT
            exit 1
          }
          
          echo "✅ Build terminé avec succès!"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify
          oc project $OPENSHIFT_PROJECT

      - name: Apply OpenShift Deployment YAML
        env:
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          echo "📄 Application des configurations de déploiement..."
          oc apply -f infrastructure/quarkus-deployment.yaml -n $OPENSHIFT_PROJECT

      - name: Deploy to OpenShift
        env:
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          echo "🔄 Mise à jour de l'image du déploiement..."
          oc set image deployment/quarkus-app quarkus-app=image-registry.openshift-image-registry.svc:5000/$OPENSHIFT_PROJECT/quarkus-app:latest
          
          echo "🔄 Redémarrage du déploiement..."
          oc rollout restart deployment/quarkus-app
          
          echo "⏳ Attente du déploiement..."
          timeout 5m oc rollout status deployment/quarkus-app -n $OPENSHIFT_PROJECT || {
            echo "❌ Déploiement échoué, vérification des logs..."
            POD_NAME=$(oc get pods -l app=quarkus-app -n $OPENSHIFT_PROJECT --sort-by=.metadata.creationTimestamp -o name | tail -n 1)
            oc logs $POD_NAME -n $OPENSHIFT_PROJECT
            exit 1
          }

      - name: Display API Route URL
        env:
          OPENSHIFT_PROJECT: ${{ secrets.OPENSHIFT_PROJECT }}
        run: |
          ROUTE=$(oc get route quarkus-route -n $OPENSHIFT_PROJECT -o jsonpath='{.spec.host}')
          echo "🔗 Votre API est disponible à: https://$ROUTE"