name: Deploy app front on OpenShift

on:
  workflow_run:
    workflows: [ "Build & Deploy Quarkus on OpenShift" ]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}
          oc project ${{ secrets.OPENSHIFT_PROJECT }}

      - name: Deploy to OpenShift
        run: |
          oc get deployment vite-oc >/dev/null 2>&1 && echo "Deployment already exists, updating..." || oc new-app vite-oc
          oc rollout restart deployment/vite-oc

      - name: Expose Route
        run: |
          oc expose svc/vite-oc --port=3000 --name=vite-oc \
          --hostname=vite-oc-lmagniez03-dev.apps.rm2.thpm.p1.openshiftapps.com

      - name: Add TLS
        run: |
          oc patch route vite-oc -p '{"spec":{"tls":{"termination":"edge"}}}
  

      - name: Create or Update HTTPS Route for Frontend
        run: |
          cat <<EOF | oc apply -f -
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: vite-oc
            namespace: ${{ secrets.OPENSHIFT_PROJECT }}
          spec:
            to:
              kind: Service
              name: vite-oc
            port:
              targetPort: 3000
            tls:
              termination: edge
          EOF

      - name: Verify Deployment and Route
        run: |
          oc get pods
          oc get routes