name: Build React App

on:
  pull_request:
    paths:
      - 'static/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to OpenShift
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}
          oc project ${{ secrets.OPENSHIFT_PROJECT }}

      - name: Build Docker Image
        run: |
          cd static/front
          oc new-build --name=vite-oc --binary --strategy=docker || echo "Build already exists"
          oc start-build vite-oc --from-dir=. --follow
