apiVersion: v1
kind: List
items:
  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: booking-reminder-24h
      namespace: gregorydhmccm-dev
      labels:
        app: m2ccm-openshiftproject
        component: reminder
        environment: production
    spec:
      # Run every hour
      schedule: "0 * * * *"
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 1
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: booking-reminder
                component: reminder-job
            spec:
              containers:
                - name: reminder-job
                  image: image-registry.openshift-image-registry.svc:5000/gregorydhmccm-dev/booking-reminder:latest
                  args: ["--type", "24h"]
                  envFrom:
                    - secretRef:
                        name: quarkus-secrets
                    - secretRef:
                        name: mail-credentials
                  env:
                    - name: QUARKUS_PROFILE
                      value: "prod"
                    - name: PROD_DB_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: quarkus-secrets
                          key: PROD_DB_USERNAME
                    - name: PROD_DB_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: quarkus-secrets
                          key: PROD_DB_PASSWORD
                    - name: KEYCLOAK_ADMIN
                      valueFrom:
                        secretKeyRef:
                          name: keycloak-secret
                          key: KEYCLOAK_ADMIN
                    - name: KEYCLOAK_ADMIN_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: keycloak-secret
                          key: KEYCLOAK_ADMIN_PASSWORD
                    - name: PROD_KC_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: quarkus-secrets
                          key: PROD_KC_SECRET
                    - name: PROD_KC_SERVICE_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: keycloak-secret
                          key: PROD_KC_SERVICE_SECRET
                  resources:
                    requests:
                      memory: "256Mi"
                      cpu: "100m"
                    limits:
                      memory: "512Mi"
                      cpu: "200m"
              restartPolicy: Never

  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: booking-reminder-1h
      namespace: gregorydhmccm-dev
      labels:
        app: m2ccm-openshiftproject
        component: reminder
        environment: production
    spec:
      # Run every 15 minutes
      schedule: "*/15 * * * *"
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 1
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: booking-reminder
                component: reminder-job
            spec:
              containers:
                - name: reminder-job
                  image: image-registry.openshift-image-registry.svc:5000/gregorydhmccm-dev/booking-reminder:latest
                  args: ["--type", "1h"]
                  envFrom:
                    - secretRef:
                        name: quarkus-secrets
                    - secretRef:
                        name: mail-credentials
                  env:
                    - name: QUARKUS_PROFILE
                      value: "prod"
                    - name: PROD_DB_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: quarkus-secrets
                          key: PROD_DB_USERNAME
                    - name: PROD_DB_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: quarkus-secrets
                          key: PROD_DB_PASSWORD
                    - name: KEYCLOAK_ADMIN
                      valueFrom:
                        secretKeyRef:
                          name: keycloak-secret
                          key: KEYCLOAK_ADMIN
                    - name: KEYCLOAK_ADMIN_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: keycloak-secret
                          key: KEYCLOAK_ADMIN_PASSWORD
                    - name: PROD_KC_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: quarkus-secrets
                          key: PROD_KC_SECRET
                    - name: PROD_KC_SERVICE_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: keycloak-secret
                          key: PROD_KC_SERVICE_SECRET
                  resources:
                    requests:
                      memory: "256Mi"
                      cpu: "100m"
                    limits:
                      memory: "512Mi"
                      cpu: "200m"
              restartPolicy: Never